// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAeD3RE2Eub7EWYbM98mSIqyOWswfygU-k",
    authDomain: "dramalist-8a577.firebaseapp.com",
    projectId: "dramalist-8a577",
    storageBucket: "dramalist-8a577.appspot.com",
    messagingSenderId: "789782385471",
    appId: "1:789782385471:web:8c6b1e384f71cccf71b98a",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xMWlNPnhNPu1KhxiP8VEuwbpFRasxjM',
    appId: '1:789782385471:android:cca3068c23f4d14d71b98a',
    messagingSenderId: '789782385471',
    projectId: 'dramalist-8a577',
    storageBucket: 'dramalist-8a577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo2Sqfm-XLiF2TCwo3hqi8BzvHPxSR46k',
    appId: '1:789782385471:ios:d011d75881c189db71b98a',
    messagingSenderId: '789782385471',
    projectId: 'dramalist-8a577',
    storageBucket: 'dramalist-8a577.appspot.com',
    // iosClientId: '174457943368-7fq2ra4qbtcs4dqhq845ub6o30eede4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.daalt',
  );
}
